/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * Api
 * SalesPulse API specification
 * OpenAPI spec version: 0.1.0
 */

export interface AiReport {
  id: number;
  createdAt: Date;
  content: string;
}
