/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * Api
 * SalesPulse API specification
 * OpenAPI spec version: 0.1.0
 */

export type CustomerLedgerEntryType = typeof CustomerLedgerEntryType[keyof typeof CustomerLedgerEntryType];


export const CustomerLedgerEntryType = {
  charge: 'charge',
  payment: 'payment',
} as const;
