/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * Api
 * SalesPulse API specification
 * OpenAPI spec version: 0.1.0
 */
import type { Customer } from './customer';
import type { CustomerLedgerEntry } from './customerLedgerEntry';

export type CustomerDetail = Customer & {
  ledger: CustomerLedgerEntry[];
};
