/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * Api
 * SalesPulse API specification
 * OpenAPI spec version: 0.1.0
 */
import type { Product } from './product';
import type { RevenuePoint } from './revenuePoint';
import type { Sale } from './sale';

export interface DashboardSummary {
  todayRevenueCents: number;
  activeDebtAccounts: number;
  totalDebtCents: number;
  monthlyExpensesCents: number;
  /**
     * Null when the active role is attendant
     * @nullable
     */
  todayProfitCents: number | null;
  lowStockProducts: Product[];
  recentSales: Sale[];
  revenueChart: RevenuePoint[];
}
