/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * Api
 * SalesPulse API specification
 * OpenAPI spec version: 0.1.0
 */
import type { ExpenseCategory } from './expenseCategory';

export interface ExpenseInput {
  category: ExpenseCategory;
  /** @minLength 1 */
  description: string;
  /** @minimum 0 */
  amountCents: number;
  expenseDate: string;
}
