/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * Api
 * SalesPulse API specification
 * OpenAPI spec version: 0.1.0
 */

export interface Product {
  id: number;
  name: string;
  categoryId: number;
  categoryName: string;
  /** @nullable */
  barcode: string | null;
  sellingPriceCents: number;
  /**
     * Omitted (null) when the active role is attendant
     * @nullable
     */
  costPriceCents: number | null;
  stockLevel: number;
  lowStockThreshold: number;
  isLowStock: boolean;
  createdAt: Date;
  updatedAt: Date;
}
