/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * Api
 * SalesPulse API specification
 * OpenAPI spec version: 0.1.0
 */

export interface RestockInput {
  /** @minimum 1 */
  quantity: number;
  /** @minimum 0 */
  costPriceCents: number;
  note?: string;
}
