/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * Api
 * SalesPulse API specification
 * OpenAPI spec version: 0.1.0
 */

export type SaleStatus = typeof SaleStatus[keyof typeof SaleStatus];


export const SaleStatus = {
  completed: 'completed',
  voided: 'voided',
} as const;
