/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * Api
 * SalesPulse API specification
 * OpenAPI spec version: 0.1.0
 */

export type StockMovementType = typeof StockMovementType[keyof typeof StockMovementType];


export const StockMovementType = {
  sale: 'sale',
  void: 'void',
  restock: 'restock',
  correction: 'correction',
} as const;
