/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * Api
 * SalesPulse API specification
 * OpenAPI spec version: 0.1.0
 */
import type { StockMovementType } from './stockMovementType';

export interface StockMovement {
  id: number;
  productId: number;
  type: StockMovementType;
  quantityChange: number;
  /** @nullable */
  reason: string | null;
  /** @nullable */
  referenceSaleId?: number | null;
  createdAt: Date;
}
